version: "3"

services:
  server:
    container_name: wellai_server
    command: sh -c "python3 manage.py migrate --noinput && 
        python manage.py collectstatic --noinput && 
        gunicorn -c backend/config/gunicorn.setting.py"
    restart: unless-stopped 
    ports:
    - 8001:8000
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env.prod
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    ports:
      - 5434:5432
    env_file:
      - .env.prod.db
  client:
    container_name: wellai_client
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/usr/src/client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: