version: "3"

services:
  server:
    container_name: wellai_server
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: sh -c "python3 manage.py migrate --noinput && 
        python3 manage.py flush --noinput &&
        python3 load_data.py &&
        python3 manage.py collectstatic --noinput && 
        gunicorn -c config/gunicorn.setting.py"
    restart: unless-stopped 
    ports:
    - 8000:8000
    volumes:
      - static_volume:/usr/src/app/.static
      - ./backend:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env.prod

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    ports:
      - 5432:5432
    env_file:
      - .env.prod.db
    
volumes:
  postgres_data:
  static_volume: