version: "3"

services:
  server:
    ports:
    - "8000:8000"
    tty: true
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: unless-stopped  

    volumes:
#. ( django 프로젝트의 루트) : web ( 도커안에 존재하는 폴더 , 사용자 지정 아님)  
      - ./backend:/usr/src/app
    depends_on:
      - db
    env_file:
      - ./.env.dev

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    env_file:
      - ./.env.dev