version: "3"

services:
  server:
    container_name: wellai_server
    restart: unless-stopped 
    ports:
    - "8000:8000"
    tty: true
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    env_file:
      - ./.env.dev
  client:
    container_name: wellai_client
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/usr/src/client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true